### ISSUE TITLE
Line Numbers

### ISSUE THREAD

**Issue by bcpeinhardt** [DanielleMaywood/glexer#16]
Would you be opposed to a PR adding line numbers to Glexer's output? We could use line numbers in the linter we're hacking on.

**Comment by DanielleMaywood** [comment]
It would probably result in a major version bump but I'm not opposed to it.

You could calculate the line number when needed with `byte_offset` by calculating how many newlines appear before reaching that offset although that has the downside of being `O(n)`.

**Comment by lpil** [comment]
It's a binary search so it's `O(log n)` with the number of lines. This could be faster overall as the extra two ints doubles the size of a token.
