### ISSUE TITLE
Support nested tuple access

### ISSUE THREAD

**Issue by arothuis** [DanielleMaywood/glexer#19]
See this issue: https://github.com/lpil/glance/issues/21

If I understand correctly, any two numbers with a dot in between are seen as floats:

```gleam
pub fn main() { wobble.12.3 }
```

is tokenized as

```gleam
[Dot(Position(22)), #(Float("12.3"), Position(23))]
```

I would expect:
```gleam
[Dot(Position(22)), #(Int("12"), Position(23), Dot(Position(25)),  #(Int("3"), Position(26))]
```

Float parsing should be excluded for accessors (i.e. a dot after a non-numeric value will never be followed by a float).

**Comment by DanielleMaywood** [comment]
Thanks for the opening the issue! 

This definitely isn't ideal, apologies if it is blocking you at all. I've got a pretty busy week ahead but I'll see if I can carve out some time to resolve this!

**Comment by arothuis** [comment]
That's a fast response! I would love to help out if possible and convenient: some pointers and a desired approach would be appreciated (unfamiliar with this library).

**Comment by DanielleMaywood** [comment]
It's been a while since I've worked on this so I can't quite recall what the best way to approach this would be.

I have a branch [`version-2`](https://github.com/DanielleMaywood/glexer/tree/version-2) that fixes an issue with integer parsing that I never got around to finishing that _might_ be useful for helping resolve this issue.

**Comment by arothuis** [comment]
I'm not sure how to approach this best. 

One option I see is to expand the dot lexer and/or create a number lexing mode for accessors (i.e. add separate dots and integers, never floats).

**Comment by DanielleMaywood** [comment]
It looks like I need to slightly overhaul this library anyways so I'm happy to tackle this

**Comment by DanielleMaywood** [comment]
I've just slightly rewritten the project as `gleam/iterator` is deprecated and the public API made use of this, I added your sample code as a test case and it appears to pass!

It's 1AM my time so I'll work on adding more tests when I'm available and will hopefully get this published sometime this week. Unfortunately this will be a major version bump so Glance will need updating.

https://github.com/DanielleMaywood/glexer/commit/789a06e2ef94d529384f77fad913c812519ed464

**Comment by arothuis** [comment]
Thanks a bunch! The new API looks good to me.

Closing this issue.
