### ISSUE TITLE
Consider unboxing positions

### ISSUE THREAD

**Issue by lpil** [DanielleMaywood/glexer#9]
Hello!

I'm finding it a little annoying having to pattern match on the `Position` records to get the position int out of them. Seeing as this type does nothing would you consider unboxing it and just returning the int?

Thanks,
Louis

**Comment by DanielleMaywood** [comment]
I definitely can do, my original thought was to have the type contain the byte offset, as well as the column/row within the source. 

Either direction would be breaking change to the API and as you're the only consumer of the library I'm aware of I'm happy to go whichever direction you'd prefer.

**Comment by lpil** [comment]
Makes sense! Either sounds good.

**Comment by DanielleMaywood** [comment]
In the latest version the field has been named `byte_offset` so there is no longer a need to pattern match on it.
